### ISSUE TITLE
Probably error in readme.md

### ISSUE THREAD

**Issue by LStan** [stellar/fca00c-asteroids#1]
In "Shoot Asteroids" it is said "you could shoot and destroy asteroids located at (53, 75) or (56, 78)". I think it should be "(53, 75) or (56, 72)"

**Comment by kalepail** [comment]
@ElliotFriend this is on your list right?

**Comment by ElliotFriend** [comment]
Thanks for pointing this out! Got my coordinates mixed up, and added in the wrong spot 👍🏻
